name = "McPack 26"
author = "ALotOfBeans"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f81a8999b7bafb6b1a5ea8e85a321eba5e6c04a0a4428a93d1e976db9273862d"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
no-internal-hashes = false
