name = "McPack 26"
author = "ALotOfBeans"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a032ade13689e427fe083505f1478ba8a8e02630f7a4b389d733f464c935a77"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
no-internal-hashes = false
