name = "McPack 26"
author = "ALotOfBeans"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e830a4674133fdb8065e1358a521f0fc6e08a90ec92a6e0d51c9be05007be8b7"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
no-internal-hashes = false
