name = "McPack 26"
author = "ALotOfBeans"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6994aa1a31ac99b54a6d1915df9475679dbaab7ee57a2bb8e2f058069ad9c97f"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
no-internal-hashes = false
