bar:
  change-interval: 200
  texts:
    - "{#0072ff}&m                                                {#00c6ff}"
    - "{#0084ff}&m                                                {#00b4ff}"
    - "{#0096ff}&m                                                {#00a2ff}"
    - "{#00a8ff}&m                                                {#0090ff}"
    - "{#00bcff}&m                                                {#007eff}"
title:
  change-interval: 1000
  texts:
    - "{#00c6ff}The GRC"
    - "{#0072ff}The GRC"
    - "{#4facfe}The GRC"