header-footer:
  enabled: true
  header:
  - '%animation:bar%'
  - ''
  - '%animation:title%'
  - ''
  - '&7Players: &f%online% &8| &7TPS: &f%tps%'
  - ''
  footer:
  - ''
  - '&7Ping: &f%ping%ms'
  - '&7Pacific Time: &f%time%'
  - ''
  - '%animation:bar%'
  disable-condition: '%world%=disabledworld'
placeholders:
  date-format: MM.dd.yyyy
  time-format: h:mm a
  time-offset: -8
  register-tab-expansion: false
placeholder-refresh-intervals:
  default-refresh-interval: 500
  '%tps%': 1000
prevent-spectator-effect:
  enabled: false
debug: false
use-online-uuid-in-tablist: true
permission-refresh-interval: 1000
proxy-support:
  enabled: true
  type: PLUGIN
  plugin:
    name: RedisBungee
compensate-for-packetevents-bug: false
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Helper
- default
belowname-objective:
  fancy-value-default: NPC
  fancy-value: '&c%health%'
  enabled: false
global-playerlist:
  update-latency: false
  enabled: false
playerlist-objective:
  title: TAB
  value: ''
  render-type: INTEGER
  enabled: true
bossbar:
  enabled: false
layout:
  enabled: false
mysql:
  enabled: false
per-world-playerlist:
  enabled: false
ping-spoof:
  enabled: false
scoreboard:
  enabled: false
scoreboard-teams:
  enabled: true
tablist-name-formatting:
  enabled: false