#The way ships are rendered by default
#Allowed Values: VANILLA, FLYWHEEL
defaultRenderer = "VANILLA"
#Recommend ship slugs in mc commands where player names could be used ex. /tp ship-name wich could pollute user autocomplete
recommendSlugsInMcCommands = true
#Renders the VS2 debug HUD with TPS
renderDebugText = false

["Block Tint"]
	#Partly fixes the block tinting issue with blocks on ships
	fixBlockTinting = false

[Tooltips]
	#Set when the Mass Tooltip is Visible
	#Allowed Values: ALWAYS, ADVANCED, DISABLED
	massTooltipVisibility = "ADVANCED"
	#Use Imperial Units to show Mass
	useImperialUnits = false

